### ISSUE TITLE
并发执行scriptEngine.eval("load(\"nashorn:mozilla_compat.js\");");出现问题

### ISSUE THREAD

**Issue by dkpp-gloomy** [HelloLyfing/lyfingScriptEngine#1]
public class ScriptEngineFactory extends BasePooledObjectFactory<ScriptEngine> {

    @Override
    public ScriptEngine create() {
        // 创建对象
        return ScriptEngineConfig.initScriptEngine();
    }

    @Override
    public PooledObject<ScriptEngine> wrap(ScriptEngine obj) {
        return new DefaultPooledObject<>(obj);
    }
}
我在该create方法时调用initScriptEngine方法初始化ScriptEngine
但是我在初始化时执行了  scriptEngine.eval("load(\"nashorn:mozilla_compat.js\");");
public static ScriptEngine initScriptEngine() {
//        ScriptEngine scriptEngine = new ScriptEngineManager().getEngineByName("nashorn");
        ScriptEngine scriptEngine = new NashornScriptEngineFactory().getScriptEngine();
        //初始化
        try {
            scriptEngine.eval("load(\"nashorn:mozilla_compat.js\");");
            scriptEngine.eval(LOAD_JS);
        } catch (ScriptException e) {
            throw new RuntimeException(e);
        }
        return scriptEngine;
    }
该方法在并发且使用war包打包方式的情况下出现了
Caused by: javax.script.ScriptException: TypeError: [object JavaPackage] is not a Java class in nashorn:mozilla_compat.js at line number 375 at column number 16
	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at com.chinacreator.c2.chs.config.ScriptEngineConfig.initScriptEngine(ScriptEngineConfig.java:35)
	... 23 common frames omitted
Caused by: jdk.nashorn.internal.runtime.ECMAException: TypeError: [object JavaPackage] is not a Java class
	at jdk.nashorn.internal.objects.NativeError.initException(NativeError.java:137)
	at jdk.nashorn.internal.objects.NativeTypeError.<init>(NativeTypeError.java:73)
	at jdk.nashorn.internal.objects.NativeTypeError.<init>(NativeTypeError.java:77)
	at jdk.nashorn.internal.objects.NativeTypeError.constructor(NativeTypeError.java:98)
	at jdk.nashorn.internal.scripts.Script$Recompilation$389$10602A$\=nashorn\!mozilla_compat.value-28(nashorn:mozilla_compat.js:375)
	at jdk.nashorn.internal.scripts.Script$379$\^eval\_.:program(<eval>:1)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
	... 28 common frames omitted
但并且我打印了引擎池中的scriptEngine对象数量为1，创建不了第二个对象
但是同样的代码在jar启动方式下无任何问题，并且对象可以达到30+或者更多

**Comment by HelloLyfing** [comment]
这个可能更多的跟nashorn特性有关，跟我这个包装关系不太大哈，你可以试下看是不是这个结论哈。

我看了下官方的介绍文档: https://www.oracle.com/technical-resources/articles/java/jf14-nashorn.html
里边对“nashorn:mozilla_compat.js”的描述为不推荐（可以搜索关键字调到对应段落），因为他每次都会往全局变量表里做引入：
"It is important to note that these functions import the symbolic references into the global scope of the JavaScript code being interpreted"，没法做多个scriptEngine间的环境变量隔离，
所以：1）最好使用官方推荐的“JavaImporter”进行类、包的引入；2）或者试下每个JVM仅初始化一次对应代码块试下。
